nome = str(input('Digite seu nome completo: '))
qtd = len(nome) - nome.count(' ')
find = nome.find(' ')
separa = nome.split()
print(f'Seu nome em maiúsculo é {nome.upper()}')
print(f'Seu nome em minúsculo é {nome.lower()}')
print(f'Seu nome tem {qtd} letras ')
print(f'Seu primeiro nome tem {find} letras')
print(f'Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras')